In [1]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import Normalizer

In [2]:
folder1=r"D:\CV_datasets\370x370\crowded"
folder2=r"D:\CV_datasets\370x370\Non-crowded"

In [3]:
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    if a is None:
        continue
    
    #resize image
    resize=(100,300)
    img=cv2.resize(a,resize)
    
    resultimage = np.zeros((100, 300))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    #gray image
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
    
    
    #initialise sift descriptor
    sift=cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(hist_image, None)
    
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    #print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'D:\CV_datasets\370x370\crowded.csv', mode='a', header=False,index=False)

In [4]:
data1 = pd.read_csv(r'D:\CV_datasets\370x370\crowded.csv',header=None,dtype='float64')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.float64) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0     1     2      3      4     5     6     7      8      9    ...  \
0       96.0   8.0   3.0   41.0   10.0   0.0   0.0  15.0  156.0   26.0  ...   
1        0.0   0.0   0.0    5.0   48.0   7.0   0.0   0.0   68.0   16.0  ...   
2        2.0   3.0  18.0    5.0    0.0   3.0  14.0   3.0   15.0    5.0  ...   
3       73.0  94.0  12.0    0.0    2.0   4.0   0.0   0.0   34.0  132.0  ...   
4       42.0  12.0   1.0    4.0  169.0  11.0   1.0   2.0  169.0   37.0  ...   
...      ...   ...   ...    ...    ...   ...   ...   ...    ...    ...  ...   
884240  17.0   2.0   0.0    3.0  130.0  17.0   0.0   0.0  145.0    6.0  ...   
884241  31.0   1.0   0.0    0.0    6.0   5.0   2.0  17.0   45.0   11.0  ...   
884242  12.0   0.0   6.0   50.0   40.0  13.0  15.0  65.0   10.0   28.0  ...   
884243  34.0   2.0   0.0    9.0   50.0   4.0   3.0  16.0  126.0    5.0  ...   
884244  78.0  27.0  15.0  146.0  136.0   3.0   0.0   7.0  139.0    6.0  ...   

         118    119    120   121   122   123    124   125  126   127  
0        9.0   11.0    0.0   0.0   0.0   0.0    0.0   0.0  0.0   0.0  
1        1.0    2.0   15.0  17.0  10.0  26.0  142.0  20.0  0.0   0.0  
2        0.0    0.0    0.0   0.0   0.0   0.0    0.0   0.0  0.0   0.0  
3        7.0   68.0   69.0  11.0   0.0   0.0    0.0   0.0  0.0   4.0  
4       20.0   12.0    0.0   0.0   0.0   0.0    0.0   0.0  0.0   0.0  
...      ...    ...    ...   ...   ...   ...    ...   ...  ...   ...  
884240   1.0    3.0    4.0   6.0   4.0   2.0   50.0  53.0  1.0   1.0  
884241   1.0   32.0    9.0  17.0  12.0  19.0   69.0  22.0  1.0   1.0  
884242   1.0   86.0  126.0   1.0   1.0   4.0   19.0   2.0  0.0  90.0  
884243   0.0  122.0   48.0   0.0   0.0  43.0  117.0   0.0  1.0  56.0  
884244  12.0   22.0    0.0   0.0   0.0   0.0    0.0   0.0  0.0   0.0  

[884245 rows x 128 columns]

In [5]:
i=0
for filename in os.listdir(folder2):
    
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    if a is None:
        continue
    
    #resize image
    resize=(100,300)
    img=cv2.resize(a,resize)
    resultimage = np.zeros((100, 300))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(hist_image, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    #print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'D:\CV_datasets\370x370\Non-crowded.csv', mode='a', header=False,index=False)

In [6]:
data2= pd.read_csv(r'D:\CV_datasets\370x370\Non-crowded.csv',header=None,dtype='float64')
data2=data2.astype(np.float64)
data2

0     1     2     3     4     5     6     7      8     9    ...  \
0        3.0   7.0  10.0  41.0  61.0  22.0   5.0   1.0   11.0  12.0  ...   
1        1.0   6.0  93.0  45.0  18.0  63.0  26.0  19.0   33.0  32.0  ...   
2        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   79.0  31.0  ...   
3        1.0   6.0   5.0   0.0   0.0   1.0   1.0   0.0   29.0  71.0  ...   
4        1.0   3.0   5.0   7.0   2.0   6.0   6.0   1.0   35.0  13.0  ...   
...      ...   ...   ...   ...   ...   ...   ...   ...    ...   ...  ...   
745834   2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   11.0   1.0  ...   
745835   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   12.0  48.0  ...   
745836   1.0   0.0   0.0   0.0   1.0   1.0   1.0   2.0    2.0   2.0  ...   
745837   2.0   1.0  23.0  32.0  54.0  95.0  66.0  20.0   12.0  34.0  ...   
745838  54.0  36.0  12.0  33.0  88.0  55.0   2.0   1.0  107.0  75.0  ...   

         118   119   120   121    122   123   124   125   126    127  
0        0.0   4.0   1.0   4.0    5.0  16.0   7.0   0.0   0.0    0.0  
1       19.0   1.0   0.0   1.0    0.0   0.0   0.0   0.0   0.0    0.0  
2        9.0  31.0  27.0   9.0    5.0  42.0  33.0   4.0  40.0  116.0  
3        1.0   3.0   3.0  40.0   84.0  56.0  13.0   3.0   2.0    2.0  
4       46.0   7.0   8.0  11.0  109.0  96.0   4.0  27.0  24.0    4.0  
...      ...   ...   ...   ...    ...   ...   ...   ...   ...    ...  
745834  40.0  23.0  41.0  15.0    2.0   1.0   4.0  18.0  31.0   21.0  
745835   4.0  39.0   6.0   3.0    4.0  15.0  55.0  57.0  26.0    9.0  
745836  33.0  27.0  54.0  98.0   67.0  19.0   2.0   1.0  22.0   32.0  
745837   5.0   0.0   1.0   2.0    1.0   2.0   1.0   0.0   0.0    0.0  
745838  16.0  27.0   1.0   1.0    0.0   0.0   0.0   0.0   1.0    1.0  

[745839 rows x 128 columns]

In [7]:
data=data1.append(data2)

In [8]:
csv_data=data.to_csv(r'D:\CV_datasets\370x370\Sift-final.csv', mode='a', header=False,index=False)

In [9]:
data= pd.read_csv(r'D:\CV_datasets\370x370\Sift-final.csv',header=None,dtype='float64')
data=data.astype(np.float64)
data

0     1     2     3      4     5     6     7      8      9    ...  \
0        96.0   8.0   3.0  41.0   10.0   0.0   0.0  15.0  156.0   26.0  ...   
1         0.0   0.0   0.0   5.0   48.0   7.0   0.0   0.0   68.0   16.0  ...   
2         2.0   3.0  18.0   5.0    0.0   3.0  14.0   3.0   15.0    5.0  ...   
3        73.0  94.0  12.0   0.0    2.0   4.0   0.0   0.0   34.0  132.0  ...   
4        42.0  12.0   1.0   4.0  169.0  11.0   1.0   2.0  169.0   37.0  ...   
...       ...   ...   ...   ...    ...   ...   ...   ...    ...    ...  ...   
1630079   2.0   0.0   0.0   0.0    0.0   0.0   0.0   0.0   11.0    1.0  ...   
1630080   0.0   1.0   0.0   0.0    0.0   0.0   0.0   0.0   12.0   48.0  ...   
1630081   1.0   0.0   0.0   0.0    1.0   1.0   1.0   2.0    2.0    2.0  ...   
1630082   2.0   1.0  23.0  32.0   54.0  95.0  66.0  20.0   12.0   34.0  ...   
1630083  54.0  36.0  12.0  33.0   88.0  55.0   2.0   1.0  107.0   75.0  ...   

          118   119   120   121   122   123    124   125   126   127  
0         9.0  11.0   0.0   0.0   0.0   0.0    0.0   0.0   0.0   0.0  
1         1.0   2.0  15.0  17.0  10.0  26.0  142.0  20.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   0.0   0.0  
3         7.0  68.0  69.0  11.0   0.0   0.0    0.0   0.0   0.0   4.0  
4        20.0  12.0   0.0   0.0   0.0   0.0    0.0   0.0   0.0   0.0  
...       ...   ...   ...   ...   ...   ...    ...   ...   ...   ...  
1630079  40.0  23.0  41.0  15.0   2.0   1.0    4.0  18.0  31.0  21.0  
1630080   4.0  39.0   6.0   3.0   4.0  15.0   55.0  57.0  26.0   9.0  
1630081  33.0  27.0  54.0  98.0  67.0  19.0    2.0   1.0  22.0  32.0  
1630082   5.0   0.0   1.0   2.0   1.0   2.0    1.0   0.0   0.0   0.0  
1630083  16.0  27.0   1.0   1.0   0.0   0.0    0.0   0.0   1.0   1.0  

[1630084 rows x 128 columns]

# Kmeans

In [10]:
# # Find K value in Kmeans :- we will used elbow method

# SSE = []

# for k in range(1,16):
#     KM_Model = KMeans(n_clusters = k )
#     KM_Model.fit(data)
#     SSE.append(KM_Model.inertia_)
#     print(k)
    
# SSE

In [11]:
# # Plot between Acc and K value.
# # X_Axis = K value
# # Y_Axis = SSE
# import matplotlib.pyplot as plt
# plt.plot(range(1,16),SSE,'*-')
# plt.xlabel("K_Value")
# plt.ylabel("Acc")

In [12]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(data)

KMeans(n_clusters=5)

In [13]:
import pickle

In [14]:
# save the model to disk
filename = r'D:\CV_datasets\370x370\Kmeans_CL_5_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [15]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5])


print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([329605, 334375, 324177, 327842, 314085], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



In [16]:
#folder1=r"D:/StrData/Str"
#folder2=r"D:\StrData\Nstr"

In [17]:
#performing kmeans prediction of the entire Crowded dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    if a is None:
        continue

    #resize image
    resize=(100,300)
    img=cv2.resize(a,resize)
    
    resultimage = np.zeros((100, 300))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    
    #gray image
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
 
    
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(hist_image, None)
    
    out=pd.DataFrame(descriptors)
    
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    if (array_double.any() == 0):
        continue
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'D:\CV_datasets\370x370\final-crowded.csv', mode='a',header=False,index=False)  #D:\StrData\FinalStr.csv

In [18]:
#performing kmeans prediction of the entire Non_Crowded dataset with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    if a is None:
        continue
    resize=(100,300)
    img=cv2.resize(a,resize)
    
    resultimage = np.zeros((100, 300))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
    
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(hist_image, None)
     
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    if (array_double.any() == 0):
        continue
    a=kmeans.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'D:\CV_datasets\370x370\final-Non-crowded.csv', mode='a',header=False,index=False)

In [19]:
#Displaying the kmeans predicted data
print("Crowded")
dat1= pd.read_csv(r'D:\CV_datasets\370x370\final-crowded.csv',header=None)   ##D:\StrData\FinalStr.csv
print(dat1)

Crowded
       0    1    2   3   4  5
0     31   94   30  81  43  0
1     23   46   28  47  40  0
2     25  107   24  90  51  0
3     71   93   69  75  56  0
4     82  103  100  90  60  0
...   ..  ...  ...  ..  .. ..
3103  29   36   45  49  33  0
3104  45   50   43  61  50  0
3105  20   51   20  54  57  0
3106  91   56  100  51  39  0
3107  28   71   20  70  34  0

[3108 rows x 6 columns]


In [20]:
print("Non-Crowded")
dat2= pd.read_csv(r'D:\CV_datasets\370x370\final-Non-crowded.csv',header=None)       #D:/StrData/FinalNstr.csv
print(dat2)

Non-Crowded
        0   1    2   3   4  5
0      62  21   78  15  42  1
1      35  24   35  17  13  1
2      23  27   23  29  51  1
3      38  12   39   8  42  1
4      76  45   91  34  38  1
...   ...  ..  ...  ..  .. ..
2996   13  18   12  19  37  1
2997   23  48   27  57  61  1
2998   78  34   76  35  98  1
2999  116  21  179  17  17  1
3000   81  64   86  41  59  1

[3001 rows x 6 columns]


In [21]:
#appending All classes into 1 csv file

A=dat1.append(dat2)

csv_data=A.to_csv(r'D:\CV_datasets\370x370\final-FV.csv', mode='a',header=False,index=False)

In [22]:
A

0    1    2   3   4  5
0      31   94   30  81  43  0
1      23   46   28  47  40  0
2      25  107   24  90  51  0
3      71   93   69  75  56  0
4      82  103  100  90  60  0
...   ...  ...  ...  ..  .. ..
2996   13   18   12  19  37  1
2997   23   48   27  57  61  1
2998   78   34   76  35  98  1
2999  116   21  179  17  17  1
3000   81   64   86  41  59  1

[6109 rows x 6 columns]

In [23]:
x = A.iloc[:,0:5].values

In [24]:
x

array([[ 31,  94,  30,  81,  43],
       [ 23,  46,  28,  47,  40],
       [ 25, 107,  24,  90,  51],
       ...,
       [ 78,  34,  76,  35,  98],
       [116,  21, 179,  17,  17],
       [ 81,  64,  86,  41,  59]], dtype=int64)

In [25]:
y = A.iloc[:,5].values

In [26]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [27]:
#Normalization
from sklearn.preprocessing import Normalizer
norm = Normalizer().fit(x)
normalized = norm.fit_transform(x)
normalized

array([[0.22426704, 0.68003553, 0.21703261, 0.58598806, 0.31108008],
       [0.27034513, 0.54069026, 0.32911581, 0.55244439, 0.47016544],
       [0.16360149, 0.7002144 , 0.15705743, 0.58896538, 0.33374705],
       ...,
       [0.5051216 , 0.22018121, 0.49216976, 0.22665713, 0.63463996],
       [0.53784459, 0.09736842, 0.82994985, 0.07882205, 0.07882205],
       [0.53161922, 0.42004482, 0.56443522, 0.26909121, 0.38722882]])

In [28]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(normalized)

In [29]:
Dhoni

array([[-1.04372864,  1.54772496, -1.05568144,  1.01592183, -0.7775437 ],
       [-0.76397404,  0.70931481, -0.38100278,  0.81812253,  0.14432783],
       [-1.41204823,  1.66913682, -1.41669877,  1.0334784 , -0.64619263],
       ...,
       [ 0.6614278 , -1.21911831,  0.60049161, -1.10296997,  1.0974286 ],
       [ 0.86009941, -1.95805613,  2.6337404 , -1.97471938, -2.12343792],
       [ 0.82230321, -0.01658252,  1.0354896 , -0.85274595, -0.33627524]])

In [30]:
from sklearn.decomposition import PCA

In [31]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [32]:
Bhumi = pca.transform(Dhoni)

In [33]:
Bhumi

array([[-2.26579303, -0.92947541,  0.31757879,  0.18551179,  0.32084762],
       [-1.33736717, -0.07302029,  0.11402097, -0.26160023, -0.2162951 ],
       [-2.71352598, -0.68397399,  0.3734981 ,  0.22181652,  0.50282087],
       ...,
       [ 1.69995343,  1.32201387, -0.11728996,  0.03477179, -0.22954366],
       [ 3.85533437, -1.32711497,  0.7203519 , -1.07392484,  1.27349514],
       [ 1.39552621, -0.45944818,  0.57060244,  0.23426702, -0.22338029]])

In [34]:
Bhumi = pd.DataFrame(Bhumi)

In [35]:
Bhumi

0         1         2         3         4
0    -2.265793 -0.929475  0.317579  0.185512  0.320848
1    -1.337367 -0.073020  0.114021 -0.261600 -0.216295
2    -2.713526 -0.683974  0.373498  0.221817  0.502821
3    -0.304338 -0.941356  0.346414  0.269992 -0.221948
4     0.056356 -1.127336  0.460335 -0.197707 -0.205432
...        ...       ...       ...       ...       ...
6104 -0.750104  2.055288 -0.167903  0.032005 -0.154234
6105 -1.527581  0.818567 -0.209241 -0.367537 -0.181754
6106  1.699953  1.322014 -0.117290  0.034772 -0.229544
6107  3.855334 -1.327115  0.720352 -1.073925  1.273495
6108  1.395526 -0.459448  0.570602  0.234267 -0.223380

[6109 rows x 5 columns]

In [36]:
Bhumi.shape

(6109, 5)

In [37]:
print(pca.explained_variance_ratio_) 

[0.59881215 0.28228661 0.0531815  0.04386237 0.02185737]


In [38]:
pca = PCA(n_components=3)
pca.fit(Dhoni)

PCA(n_components=3)

In [39]:
# save the model to disk
filename = r'D:\CV_datasets\370x370\PCA_3_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [40]:
Bhumi = pca.transform(Dhoni)

In [41]:
Bhumi

array([[-2.26579303, -0.92947541,  0.31757879],
       [-1.33736717, -0.07302029,  0.11402097],
       [-2.71352598, -0.68397399,  0.3734981 ],
       ...,
       [ 1.69995343,  1.32201387, -0.11728996],
       [ 3.85533437, -1.32711497,  0.7203519 ],
       [ 1.39552621, -0.45944818,  0.57060244]])

In [42]:
Bhumi.shape

(6109, 3)

In [43]:
print(pca.explained_variance_ratio_) 

[0.59881215 0.28228661 0.0531815 ]


In [44]:
Bhumi = pd.DataFrame(Bhumi)

In [45]:
Bhumi

0         1         2
0    -2.265793 -0.929475  0.317579
1    -1.337367 -0.073020  0.114021
2    -2.713526 -0.683974  0.373498
3    -0.304338 -0.941356  0.346414
4     0.056356 -1.127336  0.460335
...        ...       ...       ...
6104 -0.750104  2.055288 -0.167903
6105 -1.527581  0.818567 -0.209241
6106  1.699953  1.322014 -0.117290
6107  3.855334 -1.327115  0.720352
6108  1.395526 -0.459448  0.570602

[6109 rows x 3 columns]

In [46]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)

In [47]:
B

0         1         2  0
0    -2.265793 -0.929475  0.317579  0
1    -1.337367 -0.073020  0.114021  0
2    -2.713526 -0.683974  0.373498  0
3    -0.304338 -0.941356  0.346414  0
4     0.056356 -1.127336  0.460335  0
...        ...       ...       ... ..
6104 -0.750104  2.055288 -0.167903  1
6105 -1.527581  0.818567 -0.209241  1
6106  1.699953  1.322014 -0.117290  1
6107  3.855334 -1.327115  0.720352  1
6108  1.395526 -0.459448  0.570602  1

[6109 rows x 4 columns]

In [48]:
csv_data=B.to_csv(r'D:\CV_datasets\370x370\final-PCA-FV.csv', mode='a',header=False,index=False)

# Training ,Testing & Classification

In [49]:
data= pd.read_csv(r'D:\CV_datasets\370x370\final-PCA-FV.csv',header=None) ##D:/StrData/FinalPCAFV.csv

data

0         1         2  3
0    -2.265793 -0.929475  0.317579  0
1    -1.337367 -0.073020  0.114021  0
2    -2.713526 -0.683974  0.373498  0
3    -0.304338 -0.941356  0.346414  0
4     0.056356 -1.127336  0.460335  0
...        ...       ...       ... ..
6104 -0.750104  2.055288 -0.167903  1
6105 -1.527581  0.818567 -0.209241  1
6106  1.699953  1.322014 -0.117290  1
6107  3.855334 -1.327115  0.720352  1
6108  1.395526 -0.459448  0.570602  1

[6109 rows x 4 columns]

In [50]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:3].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,3]
print("Y values")
print(y)

X values
[[-2.26579303 -0.92947541  0.31757879]
 [-1.33736717 -0.07302029  0.11402097]
 [-2.71352598 -0.68397399  0.3734981 ]
 ...
 [ 1.69995343  1.32201387 -0.11728996]
 [ 3.85533437 -1.32711497  0.7203519 ]
 [ 1.39552621 -0.45944818  0.57060244]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
6104    1
6105    1
6106    1
6107    1
6108    1
Name: 3, Length: 6109, dtype: int64


In [167]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

# Decision Tree Classifier

In [168]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = r'D:\CV_datasets\370x370\model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the target variable using testing variables
y_pred1 = model1.predict(x_test)
#Results


In [169]:

recall_sensitivity = metrics.recall_score(y_test,y_pred1, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred1, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred1)*100)
print("Training Accuracy ",accuracy_score(y_train,model1.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred1))
print("Recall Score:",metrics.recall_score(y_test, y_pred1))
print("F1 Score:",metrics.f1_score(y_test, y_pred1))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  76.84124386252046
Training Accuracy  93.34970329445468
Precision Score: 0.7582781456953642
Recall Score: 0.7697478991596639
F1 Score: 0.7639699749791492
Sensitivity: 0.7697478991596639
Specificity: 0.7671451355661882


In [170]:
#Recognition &Validation
#Assigning path with any any class image
data=[]
path=r"C:\Users\ADMIN\TY_ET_A3__63_65_77_Crowd_detection(before_resizing)\crowd-detection_dataset\104.jpg"


#Repeated the process of image pre-processing and feature extraction
a=cv2.imread(path)
#print(a.shape)
if a is None:
    print("X")


#resize image
resize=(120,350)
img=cv2.resize(a,resize)
resultimage = np.zeros((100, 300))
#normalizing the given image using normalize() function
nimg = cv2.normalize(img,resultimage,0, 255, cv2.NORM_MINMAX)
    
gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
hist_image=cv2.equalizeHist(gray)

#initialise sift descriptor
sift = cv2.xfeatures2d.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(hist_image, None)

#normalizing sift features 
#norm = Normalizer()
#normalized = norm.fit_transform(descriptors)


#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)

#initialise Kmeans and create 5 clusters


#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the histogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2,3,4,5])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (119, 128)
Histogram:
     0   1   2  3   4
0  38  12  26  8  35


In [171]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [172]:
Mukta

array([[0., 0., 0., 0., 0.]])

In [173]:
Mukta.shape

(1, 5)

In [174]:
MB = pca.transform(Mukta)

In [175]:
MB.shape

(1, 3)

In [176]:
MB

array([[2.80424505e-16, 1.98843220e-17, 6.48706463e-17]])

In [177]:
#prediction
y_preddt = model1.predict(MB)

#prints the prediction of the class
print(y_preddt)

[1]


# SVM

In [178]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
model5 = DhoniSVM_LK.fit(x_train, y_train)

In [179]:
filename = r'D:\CV_datasets\370x370\SVC_RBF_PCA_3.sav'
pickle.dump(model5, open(filename, 'wb'))

In [180]:
model5

SVC()

In [181]:
y_pred5 = model5.predict(x_test)
y_pred5

In [183]:
from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(y_test, y_pred5)
cm1

In [186]:
from sklearn.metrics import accuracy_score
recall_sensitivity = metrics.recall_score(y_test,y_pred5, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred5, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred5)*100)
print("Training Accuracy ",accuracy_score(y_train,model5.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred5))
print("Recall Score:",metrics.recall_score(y_test, y_pred5))
print("F1 Score:",metrics.f1_score(y_test, y_pred5))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  83.38788870703763
Training Accuracy  80.09003478616738
Precision Score: 0.831081081081081
Recall Score: 0.826890756302521
F1 Score: 0.8289806234203875
Sensitivity: 0.826890756302521
Specificity: 0.8405103668261563


In [187]:
#y_pred1 = model1.predict(MB) 
y_predsvm =model5.predict(MB) 

#prints the prediction of the class
print(y_predsvm)

[0]


In [201]:
model6 = SVC(kernel='linear')
model6.fit(x_train, y_train)

SVC(kernel='linear')

In [202]:
y_pred6 = model6.predict(x_test)

In [203]:
from sklearn.metrics import accuracy_score
recall_sensitivity = metrics.recall_score(y_test,y_pred6, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred6, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred6)*100)
print("Training Accuracy ",accuracy_score(y_train,model6.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred6))
print("Recall Score:",metrics.recall_score(y_test, y_pred6))
print("F1 Score:",metrics.f1_score(y_test, y_pred6))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  82.65139116202947
Training Accuracy  79.94679762635563
Precision Score: 0.8207705192629816
Recall Score: 0.8235294117647058
F1 Score: 0.8221476510067114
Sensitivity: 0.8235294117647058
Specificity: 0.8293460925039873


In [204]:
model7 = SVC(kernel='poly')
model7.fit(x_train, y_train)

SVC(kernel='poly')

In [205]:
y_pred7 = model7.predict(x_test)

In [206]:
from sklearn.metrics import accuracy_score
recall_sensitivity = metrics.recall_score(y_test,y_pred7, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred7, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred7)*100)
print("Training Accuracy ",accuracy_score(y_train,model7.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred7))
print("Recall Score:",metrics.recall_score(y_test, y_pred7))
print("F1 Score:",metrics.f1_score(y_test, y_pred7))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  79.95090016366612
Training Accuracy  77.92101493758953
Precision Score: 0.85
Recall Score: 0.7142857142857143
F1 Score: 0.776255707762557
Sensitivity: 0.7142857142857143
Specificity: 0.8803827751196173


# Random Forest

In [188]:
#Random Forest CLassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model4 = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=None, min_samples_split=2,
                                min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='log2',
                                max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, 
                                n_jobs=None, random_state=2, verbose=0, warm_start=False, class_weight=None, 
                                ccp_alpha=0.0, max_samples=None)
filename = r'D:\CV_datasets\370x370\model4.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model4.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred4 = model4.predict(x_test)
#Results
#print(y_pred4)

In [189]:
recall_sensitivity = metrics.recall_score(y_test,y_pred4, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred4, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred4)*100)
print("Training Accuracy ",accuracy_score(y_train,model4.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred4))
print("Recall Score:",metrics.recall_score(y_test, y_pred4))
print("F1 Score:",metrics.f1_score(y_test, y_pred4))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  81.99672667757774
Training Accuracy  99.87722529158994
Precision Score: 0.8161888701517707
Recall Score: 0.8134453781512605
F1 Score: 0.8148148148148147
Sensitivity: 0.8134453781512605
Specificity: 0.8261562998405104


In [190]:
y_predRF = model4.predict(MB)

#prints the prediction of the class
print(y_predRF)

[0]


# KNN

In [192]:
from sklearn.neighbors import KNeighborsClassifier
model2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model2.fit(x_train, y_train)

KNeighborsClassifier()

In [193]:
y_pred2 = model2.predict(x_test)

In [194]:
recall_sensitivity = metrics.recall_score(y_test,y_pred2, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred2, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred2)*100)
print("Training Accuracy ",accuracy_score(y_train,model2.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred2))
print("Recall Score:",metrics.recall_score(y_test, y_pred2))
print("F1 Score:",metrics.f1_score(y_test, y_pred2))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  80.36006546644845
Training Accuracy  83.48680171884591
Precision Score: 0.7953410981697171
Recall Score: 0.8033613445378152
F1 Score: 0.7993311036789298
Sensitivity: 0.8033613445378152
Specificity: 0.8038277511961722


In [195]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred2)

In [196]:
y_predknn = model2.predict(MB)

#prints the prediction of the class
print(y_predknn)

[1]


# Logistic Regression

In [197]:
from sklearn.linear_model import LogisticRegression
model3 = LogisticRegression(random_state = 0)
model3.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [198]:
y_pred3 = model3.predict(x_test)

In [199]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred3)
recall_sensitivity = metrics.recall_score(y_test,y_pred3, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred3, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred3)*100)
print("Training Accuracy ",accuracy_score(y_train,model3.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred3))
print("Recall Score:",metrics.recall_score(y_test, y_pred3))
print("F1 Score:",metrics.f1_score(y_test, y_pred3))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  82.40589198036007
Training Accuracy  79.78309801514222
Precision Score: 0.8135313531353136
Recall Score: 0.8285714285714286
F1 Score: 0.8209825145711906
Sensitivity: 0.8285714285714286
Specificity: 0.8197767145135566


In [200]:
y_predlr = model3.predict(MB)

#prints the prediction of the class
print(y_predlr)

[1]
